import s2sphere
import numpy as np
import pandas as pd
from tqdm import tqdm

def get_s2_cell_id(lat, lng, level=30):
    """
    Returns the S2 cell ID for a given latitude and longitude at a specific level.
    """
    p = s2sphere.LatLng.from_degrees(lat, lng)
    return s2sphere.CellId.from_lat_lng(p).parent(level)

def get_cell_vertices(cell_id):
    """
    Returns the four vertices of an S2 cell as (longitude, latitude) tuples.
    Used for plotting cell boundaries.
    """
    cell = s2sphere.Cell(cell_id)
    vertices = []
    for i in range(4):
        vertex = s2sphere.LatLng.from_point(cell.get_vertex(i))
        vertices.append((vertex.lng().degrees, vertex.lat().degrees))
    return vertices

def fast_assign_label(point_s2_id, lookup_dict):
    """
    Assigns a label to a point by finding its parent cell in the lookup dictionary.
    Checks from the most specific level (30) up to the root.
    """
    for lvl in range(30, -1, -1):
        parent_token = point_s2_id.parent(lvl).to_token()
        if parent_token in lookup_dict:
            return parent_token
    return '-1'

def perform_train_val_split(df, split_ratio=0.85, random_seed=42):
    """
    Splits the dataframe into training and validation sets.
    """
    np.random.seed(random_seed)
    train_len = int(split_ratio * len(df))
    train_indices = np.sort(np.random.choice(len(df), size=train_len, replace=False))
    
    df['is_train'] = 0
    df.loc[train_indices, 'is_train'] = 1
    
    df_train = df[df['is_train'] == 1].copy()
    df_val = df[df['is_train'] == 0].copy()
    return df_train, df_val

def create_cell_center_dataset(configs: list, trained_partitions: dict) -> pd.DataFrame:
    """
    Reconstructs the center coordinates for S2 cells generated by different partitioning configurations
    and combines them into a single DataFrame.
    """
    cell_centers_by_config = {}

    print("Reconstructing cell centers for each configuration...")

    for cfg in configs:
        name = cfg['name']
        leaf_cells = trained_partitions[name]

        cell_centers = []
        for leaf in tqdm(leaf_cells, desc=f"   Processing {name} cells"):
            cell_id = leaf['cell_id']
            # Using s2sphere logic to get center
            latlng = cell_id.to_lat_lng()
            center_lat = latlng.lat().degrees
            center_lng = latlng.lng().degrees
            cell_centers.append({
                'cell_id_token': cell_id.to_token(),
                'center_latitude': center_lat,
                'center_longitude': center_lng,
                'count': leaf['count']
            })
        cell_centers_by_config[name] = pd.DataFrame(cell_centers)

    # Create a single combined DataFrame
    all_cell_data = []

    for cfg_name, df_centers in cell_centers_by_config.items():
        df_centers['config_name'] = cfg_name
        all_cell_data.append(df_centers)

    # Concatenate all DataFrames into one
    combined_cell_df = pd.concat(all_cell_data, ignore_index=True)

    print("Combined Cell Centers DataFrame created.")
    print(f"Total rows in the combined DataFrame: {len(combined_cell_df)}")

    return combined_cell_df